Feat/more user data
dval-in/dvalin-backend pull request #104
Opened 2024-05-28 13:08 UTC by LudovicMalot

2024-05-29 14:35 UTC, maalni requested changes

2024-05-29 14:35 UTC, maalni commented on src/routes/character/routes.ts
> +				return;
Respond to frontend

2024-05-29 14:35 UTC, maalni commented on src/routes/character/routes.ts
> +			await saveCharacter(character, user.uid);
Verify uid here aswell

2024-05-29 14:35 UTC, maalni commented on src/routes/user/routes.ts
> +					ar: account.ar || 60,
Can you change the default to 1?

2024-05-29 14:35 UTC, maalni commented on src/routes/user/routes.ts
> +					wl: account.wl || 6
Same here. Default to 1

2024-05-29 14:35 UTC, maalni commented on src/routes/user/routes.ts
> +		this.app.post('/importsync', async (req: Request, res: Response) => {
This operation should probably be done inside a queue since its pretty hefty

2024-05-29 14:35 UTC, maalni commented on src/routes/user/routes.ts
> +						(wish) => !currentWishes.some((w) => w.id === wish.id)
If this check tries to prevent duplicates it will only do so for dvalin imports since paimon doesnt export the original wish id iirc

2024-05-29 14:35 UTC, maalni commented on src/worker/wishHistoryWorker.ts
> +		await saveCharactersConstellation(characterUpdate, uid);
Constellation value will vary depending on wishes returned from hoyo. Will also overwrite manually changed wishes

2024-05-29 14:43 UTC, LudovicMalot commented on prisma/schema.prisma
> +  preStage            Int?
previous achievement stage if it exist

2024-05-30 14:29 UTC, maalni commented on prisma/schema.prisma
> +  preStage            Int?
Hmm then im not sure if it needs to be stored since that already exists in data repo.

2024-06-02 11:19 UTC, LudovicMalot commented on src/routes/user/routes.ts
> +						(wish) => !currentWishes.some((w) => w.id === wish.id)
<img width="394" alt="image" src="https://github.com/dval-in/dvalin-backend/assets/95631444/95e4c44d-a6b3-44c7-85a4-cf340e350257">
paimon actually do share the original

2024-06-02 12:55 UTC, maalni commented on src/routes/user/routes.ts
> +						(wish) => !currentWishes.some((w) => w.id === wish.id)
![Screenshot 2024-06-02 144513](https://github.com/dval-in/dvalin-backend/assets/14811944/22acd3d4-c6e5-4f7e-9199-edbd1c201b59)
Wishes don't have their respective id :/ 

For that reason we set wish number to its current position in the array:
![Screenshot 2024-06-02 144846](https://github.com/dval-in/dvalin-backend/assets/14811944/05e569b7-c54e-4df4-b8cd-1b608409efcd)

So wish.number will only match wish.id by accident which leads to duplicates.
You would need to match key, date and pity to conclude if that wish is already saved in db (which would still be wonky if you for example pulled 3 5* back to back in a 10 pull due to key, date and pity matching)

2024-06-05 11:40 UTC, maalni commented on src/db/achievements.ts
> +				achieved: achievement.achieved
i think you dont need to split the achievement object

2024-06-05 11:40 UTC, maalni commented on src/db/character.ts
> +			key: key,
Same as achievements object. No need to split

2024-06-05 11:40 UTC, maalni commented on src/db/character.ts
> +				key: character.key,
Same here

2024-06-05 11:40 UTC, maalni commented on src/db/genshinAccount.ts
> +			wl: genshinAccount.wl
Same here

2024-06-05 11:40 UTC, maalni commented on src/db/weapons.ts
Can this be deleted?

2024-06-05 11:40 UTC, maalni commented on prisma/schema.prisma
> +  manualConstellations Int?
What is this used for?

2024-06-05 12:09 UTC, LudovicMalot commented on src/db/character.ts
> +				key: character.key,
uid is not in char so for this one I kinda need

2024-06-05 12:10 UTC, LudovicMalot commented on prisma/schema.prisma
> +  manualConstellations Int?
when user add or remove const it's saved as "manual"

2024-06-05 12:11 UTC, LudovicMalot commented on prisma/schema.prisma
> +  manualConstellations Int?
not sure if it's needed or if we want to stack all in const instead. but that avoid override from the wish import

2024-06-05 20:55 UTC, maalni commented on src/db/character.ts
> +				key: character.key,
Then you can spread the whole object and add uid. This way when char object changes you dont need to change these lines to accomodate.
{...character, uid: uid}

2024-06-06 21:18 UTC, maalni reviewed
Need to take a look at profile import code on desktop

2024-06-06 21:18 UTC, maalni commented on src/db/genshinAccount.ts
> +	await prisma.config.create({
This can be created in the same query as genshinAccount

2024-06-06 21:18 UTC, maalni commented on src/db/weapons.ts
> +			...restData
If its just create: {...restData} then u can use create: restData

2024-06-06 21:18 UTC, maalni commented on src/queues/importSyncQueue.ts
> +const scheduler = new ToadScheduler();
I think multiple instances of this are ok (if it does return multiple instances)

2024-06-06 21:18 UTC, maalni commented on src/utils/sync.ts
> +				};
This is still todo?

2024-06-06 21:18 UTC, maalni commented on src/utils/websockets.ts
> +declare module 'socket.io' {
Move this to root .d.ts

2024-06-06 22:06 UTC, maalni commented on src/utils/sync.ts
> +				await createMultipleWishes(newWishes);
Can this fail if an genshin account for specified uid doesnt exist?

2024-06-06 22:06 UTC, maalni commented on src/worker/importSyncWorker.ts
> +			if (!userProfile) {
Can userProfile be undefined?

2024-06-06 22:06 UTC, maalni commented on src/worker/importSyncWorker.ts
> +			const isPaimon = userProfile.format === 'paimon';
You can move this into the importSync function

2024-06-06 22:06 UTC, maalni commented on src/worker/wishHistoryWorker.ts
> +			config?.autoRefine5 || false
Why can config be null?

2024-06-07 11:04 UTC, LudovicMalot commented on src/types/websocket.ts
> +export type QueryKey = 'fetchHoyoWishhistoryStatus' | 'fetchUserProfile' | 'userSyncStatus';
yeah well i added one extra

2024-06-07 11:12 UTC, LudovicMalot commented on src/worker/wishHistoryWorker.ts
> +			config?.autoRefine5 || false
It can't be ts though it could.

2024-06-15 03:11 UTC, LudovicMalot commented on src/handlers/user/wishesHandler.ts
> +		? formatPaimonWishes(allWishes as unknown as PaimonWish[], uid, bktree, dataIndex)
IMappedWish[]

2024-06-15 03:16 UTC, LudovicMalot commented on src/handlers/user/wishesHandler.ts
> +			throw new Error('Paimon import requires initial import on Dvalin website');
It will be more annoying. If they are using paimon's wish import, it probably won't be too hard for them to do the same on dvalin. the longer they wait, we will have "wrong" wishes

2024-06-15 03:21 UTC, LudovicMalot commented on src/handlers/user/wishesHandler.ts
> +		? formatPaimonWishes(allWishes as unknown as PaimonWish[], uid, bktree, dataIndex)
but tried smth different so I don't typecast

2024-06-15 09:45 UTC, maalni commented on src/handlers/user/wishesHandler.ts
> +const formatRegularWishes = (wishes: any[], uid: string): Omit<Wish, 'createdAt'>[] => {
Does this need to be any aswell?

2024-06-15 09:45 UTC, maalni commented on src/handlers/user/wishesHandler.ts
> +};
```
const isPaimonWish = (wish: unknown): wish is PaimonWish => {
    if(wish.hasOwnProperty(type) && wish.hasOwnProperty(code)){
        return wish.type !== undefined && wish.code !== undefined;
    }

    return false;
};
```

2024-06-15 09:45 UTC, maalni commented on src/handlers/user/wishesHandler.ts
>  		: formatRegularWishes(allWishes, uid);
You can typeguard here and if isPaimonWish is successfull use formatPaimonWishes instead of formatRegularWishes.
Or you can typeguard the imported file at first and trust this instead of the isPaimon flag provided by the requester

2024-06-15 09:45 UTC, maalni commented on src/handlers/user/wishesHandler.ts
> +	return wishes.filter(isPaimonWish).map((wish) => ({
See comment above

2024-06-16 08:10 UTC, maalni commented on src/handlers/response.handler.ts
> +	const responseData = !config.DEBUG ? removeIds(data) : data;
Do we really need to remove id's from the response? They are only sent once you're authenticated so it doesnt really matter, does it?

2024-06-16 08:10 UTC, maalni commented on src/services/auth.service.ts
> +	async getUserInfo(userId: string) {
Why wrap getAuthsByUser in a function which only returns the value?

2024-06-16 08:10 UTC, maalni commented on src/db/models/auth.ts
> +export const getUserById = async (id: string): Promise<Result<Auth, Error>> => {
getAuthById

tbh im not sure if we ever want to retrieve an auth by id

2024-06-16 08:10 UTC, maalni commented on src/routes/auth/discordOAuth.route.ts
> +						return cb(createAuthResult.error, undefined);
Still return user here since they are already authenticated. Only the creation failed. Maybe we should check before creation, if such an auth already exists

2024-06-18 15:50 UTC, maalni requested changes

2024-06-18 15:50 UTC, maalni commented on src/worker/wish.worker.ts
> +};
why wrap wishService.processWishJob?

2024-06-18 15:50 UTC, maalni commented on src/worker/userProfileSync.worker.ts
> +	return userProfileService.syncUserProfile(userProfile, isPaimon, bkTree, dataIndex);
Just call them in the worker

2024-06-18 15:50 UTC, maalni commented on src/services/data.service.ts
> +				}
why double wrap try and catch?

2024-06-18 15:50 UTC, maalni commented on src/services/userProfile.service.ts
> +		}
Is this try & catch still necessary?

2024-06-18 15:50 UTC, maalni commented on src/handlers/websocket/websocket.handler.ts
> +			const accountsResult: Result<any, Error> = await getGenshinAccountsByUser(user.userId);
any. Let this const inherit its type from assignment

2024-06-18 15:50 UTC, maalni commented on src/handlers/websocket/websocket.handler.ts
> +					if (!accounts || accounts.filter((e: any) => e.uid === data.uid).length === 0) {
any

2024-06-18 15:50 UTC, maalni commented on src/services/character.service.ts
> +	async saveCharacterForUser(userId: string, character: any): Promise<Result<void, Error>> {
any => unknown

2024-06-18 15:50 UTC, maalni commented on src/services/weapon.service.ts
> +	async saveWeaponForUser(userId: string, weapon: any): Promise<Result<void, Error>> {
any => unknown

2024-06-18 15:50 UTC, maalni commented on src/services/wish.service.ts
> +	async getJobStatus(userId: string): Promise<Result<{ state: string; data?: any }, Error>> {
any

2024-06-18 15:50 UTC, maalni commented on src/services/data.service.ts
> +					console.error(`[server] Missing field in file: ${file.name}`, error);
logToConsole

2024-06-18 15:50 UTC, maalni commented on src/services/data.service.ts
> +				console.error(`[server] Failed to fetch ${type} file: ${file.name}`, fileError);
logToConsole

2024-06-18 15:50 UTC, maalni commented on src/worker/userProfileSync.worker.ts
> +		console.error('Failed to get WebSocketService instance:', wssResult.error.message);
logToConsole

2024-06-18 15:50 UTC, maalni commented on src/worker/userProfileSync.worker.ts
> +		console.error(err);
logToConsole

2024-06-18 15:50 UTC, maalni commented on src/worker/wish.worker.ts
> +		console.error('Failed to get WebSocketService instance:', wssResult.error.message);
logToConsole

2024-06-18 15:50 UTC, maalni commented on src/worker/wish.worker.ts
> +		console.error(err);
logToConsole

2024-06-19 03:06 UTC, LudovicMalot commented on src/handlers/userProfile/wishes.handler.ts
> +		rankType: wish.rate ? '3' : getRarity(bktree.search(wish.id)[0].word, wish.type, dataIndex)
BKTree search is log n
Very hard to be better

2024-06-20 09:28 UTC, maalni commented on src/services/wish.service.ts
> +	async getJobStatus(userId: string): Promise<Result<{ state: string; data?: unknown }, Error>> {
data?: {completedTimestamp: string, rateLimitDuration: number} || {count: number}

2024-06-20 10:25 UTC, maalni approved these changes

2024-06-20 10:25 UTC, merged