feat: added bannerdata and store
dval-in/dvalin-backend pull request #106
Opened 2024-06-01 08:35 UTC by teehee567

in progress
- [x] pull bannerdata from git
- [x] update bannerdata on interval
- [ ] get bannerid from time
- [x] add bannerid to prisma

2024-06-06 22:19 UTC, maalni requested changes

2024-06-06 22:19 UTC, maalni commented on prisma/schema.prisma
> +  bannerId       String
You need to set bannerId nullable or migrate old data so it includes non-null bannerId

2024-06-06 22:19 UTC, maalni commented on src/utils/bannerIdentifier.ts
> +		const response = await axios.get(
axios.get<RawBanners>

2024-06-06 22:19 UTC, maalni commented on src/utils/bannerIdentifier.ts
> +		return parseBannerDates(response.data as RawBanners);
No need to cast type

2024-06-06 22:19 UTC, maalni commented on src/utils/bannerIdentifier.ts
> +		const found = bannerdata!.find(
This will crash if bannerdata is undefined

2024-06-06 22:19 UTC, maalni commented on src/utils/bannerIdentifier.ts
> +			throw new Error('banner not found in banner data');
Dont throw. Return undefined instead and handle accordingly

2024-06-06 22:19 UTC, maalni commented on src/worker/bannerDataWorker.ts
would move this to service folder since its not a queue/worker

2024-06-06 22:19 UTC, maalni commented on src/worker/bannerDataWorker.ts
> +			wishHistoryRoute.isInitialised = true;
Set BannerService.isInitialized instead

2024-06-06 22:19 UTC, maalni commented on src/worker/bannerDataWorker.ts
> +	}
Use ToadScheduler instead. More robust than just setInterval

2024-06-07 05:12 UTC, teehee567 commented on src/utils/bannerIdentifier.ts
> +		const found = bannerdata!.find(
yea i was thinking of only uysing this when putting new wishes into the database so then when we need wishes on hte frontend the bannerid is guaranteed to be there

2024-07-18 13:21 UTC, maalni requested changes

2024-07-18 13:21 UTC, maalni commented on src/utils/bannerIdentifier.ts
> +const indefiniteDate = new Date('9999-12-31');
ehe!
ehe te nandayo?!?!?!

2024-07-18 13:21 UTC, maalni commented on src/utils/bannerIdentifier.ts
> +				banner.duration === 'TBA' ? indefiniteDate : new Date(banner.startDuration),
Can banners have unannounced dates in data?

2024-07-18 13:21 UTC, maalni commented on src/utils/bannerIdentifier.ts
> +		return 'BANNERNOTFOUND';
return undefined

2024-07-18 13:21 UTC, maalni commented on src/worker/wish.worker.ts
> +};
Not really fond of this while loop. Maybe a subscriber pattern would help?

2024-08-06 07:01 UTC, LudovicMalot commented on src/worker/wish.worker.ts
> +};
@maalni i dunno if this needed, server wont be ready until its init anyway (in `main.ts`)

2024-08-06 07:06 UTC, maalni commented on src/worker/wish.worker.ts
> +};
While frontend respects backend state you could still send malicious requests during init which needs to be caught by this to avoid sideeffects. But i dont like solving this problem with a while loop

2024-08-06 07:07 UTC, LudovicMalot commented on src/worker/wish.worker.ts
> +};
> While frontend respects backend state you could still send malicious requests during init which needs to be caught by this to avoid sideeffects. But i dont like solving this problem with a while loop

what about a middleware that say stfu to any request until state is ready ?

2024-08-06 07:19 UTC, maalni commented on src/worker/wish.worker.ts
> +};
Ohhh that would be brilliant! Then there is no need to check init etc in every service.

2024-08-06 07:37 UTC, LudovicMalot commented on src/worker/wish.worker.ts
> +};
done

2024-08-06 08:29 UTC, maalni commented on src/handlers/dataStructure/BKTree.ts
> +	public isInitialized: boolean = false;
Is this always false?
This should be set to true in constructor after initial data is inserted

2024-08-06 08:34 UTC, maalni commented on src/handlers/userProfile/paimonWishes.handler.ts
> +				['301', '302'].includes(wish.gachaType) && wish.isFeatured && prev5StarIsFeatured;
Move ['301', '302'] into const

2024-08-06 08:36 UTC, maalni commented on src/main.ts
> +		return res.status(503).json({ state: 'INITIALIZING' });
sendErrorResponse

2024-08-08 16:31 UTC, maalni requested changes

2024-08-08 16:31 UTC, maalni commented on src/main.ts
> +});
What is this used for?

2024-08-08 16:31 UTC, maalni commented on src/main.ts
> +};
This should be in data service

2024-08-08 16:31 UTC, maalni commented on src/main.ts
> +		serverShouldListen = false;
No need to stop responding. Backend can serve old data just fine while doing atomic replace. Otherwise set dataservice to initializing

2024-08-08 16:31 UTC, maalni commented on src/main.ts
> +};
put this in app.use

2024-08-08 16:31 UTC, maalni commented on src/main.ts
> +	}
no need to exclude root. Just let root always serve running state

2024-08-08 16:31 UTC, maalni commented on src/main.ts
> +	}
Shouldnt it refresh data if origin matches?

2024-08-08 16:31 UTC, maalni commented on src/services/wish.service.ts
> +		const uid = returnvalue[0]?.uid;
Yes this stops backend from crashing but why was the return value missing the uid. Did Hoyo not return it?

2024-08-08 16:31 UTC, maalni commented on src/routes/banner/banner.routes.ts
> +			sendSuccessResponse(res, bannerData);
This can throw duplicate header. Maybe we should disable the return rule and always return infront of sendResponse

2024-08-08 16:31 UTC, maalni commented on src/services/banner.service.ts
> +	}
constructor?

2024-08-08 16:31 UTC, maalni commented on src/services/data.service.ts
> +	}
constructor?

2024-08-10 01:14 UTC, LudovicMalot commented on src/routes/banner/banner.routes.ts
> +			sendSuccessResponse(res, bannerData);
yeah will be better

2024-08-10 01:16 UTC, LudovicMalot commented on src/main.ts
> +	}
forgot the !

2024-08-12 10:39 UTC, maalni approved these changes

2024-08-12 10:43 UTC, merged