feat: implementation of the wish import, similar to paimon.moe
dval-in/dvalin-backend pull request #5
Opened 2024-03-26 17:25 UTC by LudovicMalot

2024-03-26 19:08 UTC, maalni requested changes

2024-03-26 19:08 UTC, maalni commented on src/utils/wishImport.ts
> +				const response = (await axios.get(url, { params })).data as hoyoWishResponse;
Dont assert Types.

```suggestion
				const response = (await axios.get<hoyoWishResponse>(url, { params })).data;
```

2024-03-26 19:08 UTC, maalni commented on src/utils/wishImport.ts
> +					}
Why delay every 5th page? Wouldnt random delay between 100-1000ms be better to avoid detection?

2024-03-26 21:20 UTC, LudovicMalot commented on src/index.ts
> +// exemple request : http://localhost:3000/wishhistory?authkey=MYO%2BmxJzieyA8xPITwQSZCl%2BMFm1fMrf9zZ9e4IIKaPrjlGnTw4U2nMOH4YTKYhKXf2d4NEPh5Vap49rDhGpku4aqm2etwVDaw5pfYEYj238xSWAddGBvJWVehL%2Bq3LbLs
very soon to be expired so i'd rather leave it here as an accurate exemple.

2024-03-26 21:21 UTC, LudovicMalot commented on src/utils/wishImport.ts
> +import axios from "axios";
Axios will be more flexible and easier for all the data fetching. We could use fetch but I feel like it's a bit more maintainable and readable with Axios

2024-03-26 21:24 UTC, LudovicMalot commented on src/utils/wishImport.ts
> +					}
five seems to be a soft spot to be sure not to get banned.i've added a random delay

2024-03-27 08:11 UTC, maalni approved these changes

2024-03-27 09:58 UTC, merged